module.exports = [
  {
    img: 'https://www.kfc.ca/Content/OnlineOrderingImages/StaticPage/story/story_28_lrg.jpg',
    name: 'Product Title',
    content: 'Brief Content',
    discount: '35%',
    instore: '3',
    price: '$1.99',
  },
  {
    img: 'https://www.kfc.ca/Content/OnlineOrderingImages/StaticPage/story/story_28_lrg.jpg',
    name: 'Product Title',
    content: 'Brief Content',
    discount: 'N/A',
    instore: '3',
    price: '$100.99',
  },
  {
    img: 'https://www.kfc.ca/Content/OnlineOrderingImages/StaticPage/story/story_28_lrg.jpg',
    name: 'Product Title',
    content: 'Brief Content',
    discount: '15%',
    instore: '3',
    price: '$21.99',
  },
  {
    img: 'https://www.kfc.ca/Content/OnlineOrderingImages/StaticPage/story/story_28_lrg.jpg',
    name: 'Product Title',
    content: 'Brief Content',
    discount: '20%',
    instore: '3',
    price: '$91.99',
  },
  {
    img: 'https://www.kfc.ca/Content/OnlineOrderingImages/StaticPage/story/story_28_lrg.jpg',
    name: 'Product Title',
    content: 'Brief Content',
    discount: '12%',
    instore: '3',
    price: '$11.99',
  },
];
